[build]
  command = "cd Frontend && npm install && npm run build"
  publish = "Frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
